### ISSUE TITLE
Issue in latest package 1.1.0

### ISSUE THREAD

**Issue by ansarikhurshid786** [matinzd/rn-bottom-sheet#5]
I just update so i am getting error as below : 

TyepError: undefined is not an object (evaluating '_this2.props.customStyle')

can you please check ?

**Comment by ansarikhurshid786** [comment]
resolved. i put empty customStyle prop in bottom drawer.

**Comment by c-fitzmaurice** [comment]
This does not solve the problem. I am still getting am undefined is not an object error for `customStyles`

**Comment by ansarikhurshid786** [comment]
Yes right, I am still facing same issue. I restart app i got same error again.

**Comment by ansarikhurshid786** [comment]
Downgrade version and use this package

`npm i rn-bottom-sheet@1.0.4 --save`

**Comment by ansarikhurshid786** [comment]
@matinzd  can you please check?

**Comment by matinzd** [comment]
> @matinzd can you please check?

I have been busy these days. Could you please make PR?

**Comment by ansarikhurshid786** [comment]
@matinzd i don't have solution. i will try.
I am still getting same error after downgrade.

**Comment by ansarikhurshid786** [comment]
@matinzd I commented customStyle. now it is working fine.

**Comment by Joeao** [comment]
This PR should fix it https://github.com/matinzd/rn-bottom-sheet/pull/6
